Archive_base: null
Case: c124_dyamond1_prod2
Dst: null
DstVgrid: null
Output_abs_dir: null
Resubmit: 122
StepBy: hour
StepN: 3
UHRtag: UHR_SO-East
day: 17
do_steps:
- false
- false
- false
- false
- false
- true
- false
- false
- false
- false
frequency: null
hour: 15
hsPat: h2i
month: 8
year: 2016
