Archive_base: null
Case: c153_topfix_ne240pg3_FMTHIST_xic_x02
Dst: null
DstVgrid: null
Output_abs_dir: null
Resubmit: -1
StepBy: month
StepN: 1
day: 99
frequency: null
hour: 99
hsPat: cam.h1i
month: 7
year: 2004
write_to_file: True
